//***********************************************************
// Getting Started - Simple Program Version 2
//
// Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
// All Rights Reserved.
//***********************************************************

// Window identifiers.
#define ID_CLIENT  0x8008    // FID_CLIENT from pmwin.h

// Command identifiers.
#define CMD_CUT    1003
#define CMD_COPY   1004
#define CMD_PASTE  1005

// Other menu-bar related identifiers.
#define ID_MENUBAR 1000
#define ID_FILE    1001
#define ID_EDIT    1002
