## Advanced Frame - Dialog Window Example             


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS = /PM:PM /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : tstdlg.exe 

tstdlg.exe : tstdlg.obj dialog.obj dlghndlr.obj tstdlg.res
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) tstdlg.obj dialog.obj dlghndlr.obj
   rc .\$*.res .\$*.exe

tstdlg.cpp   :
dialog.cpp   : dialog.hpp dlghndlr.hpp
dlghndlr.cpp : dlghndlr.hpp

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp

{.}.rc.res:
   rc -r .\$*.rc
