/************************************************************
/ Menus - Using a Menu Cursor     
/
/ Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
/ All Rights Reserved.
************************************************************/
#define ID_STATUS          1002
                          
#define MAIN_MENU          1010
#define POPUP_MENU         1011
#define EDIT_MENU          1012
#define EXAMPLE_MENU       1013

#define MI_FILE            1050
#define MI_NEW             1051
#define MI_OPEN            1052
#define MI_SAVE            1053
#define MI_SAVEAS          1054
#define MI_EDIT            1055
#define MI_UNDO            1056
#define MI_CUT             1057
#define MI_COPY            1058
#define MI_PASTE           1059
#define MI_EXAMPLE         1060
#define MI_BITMAP          1061
#define MI_HELP            1062
#define MI_GENERAL_HELP    1063
#define MI_SEPARATOR       1064

                          

