## Canvas  - IMultiCellCanvas Implementation of Lunch Dialog 


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS = /PM:PM /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : mclunch.exe 

mclunch.exe : mclunch.obj 
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) mclunch.obj

mclunch.cpp: lunch.h pushbtns.hpp

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp
