## Data Types - Replacing the IString's IBuffer Object 


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS =  /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : mybuffer.exe 

mybuffer.exe : mybuffer.obj 
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) mybuffer.obj

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp
