/************************************************************
/ Reusable Handlers - Simple Command Handler
/
/ Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
/ All Rights Reserved.
************************************************************/

#define ID_POPUP           100

// Command identifiers.
#define ID_ONE_BEEP_CMD    1001
#define ID_TWO_BEEP_CMD    1002
#define ID_THREE_BEEP_CMD  1003
