/************************************************************
/ Container - Combined Tree and Details View
/
/ Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
/ All Rights Reserved.
************************************************************/
#define EX_PARTLIST_FRAME   1000
#define EX_PARTLIST_CANVAS  1001
#define EX_PARTLIST_TREE    1002
#define EX_PARTLIST_DETAILS 1003
#define EX_COLUMN_TRACEABLE 1004
#define EX_COLUMN_ENABLED   1005
#define EX_COLUMN_GENTRACE  1006
#define EX_COLUMN_TRIGGER   1007


#define EX_PARTLIST_LEFTCANVAS      1010
#define EX_PARTLIST_RIGHTCANVAS     1011
#define EX_PARTLIST_DETAILSPAD      1012
#define EX_PARTLIST_TREESCROLLHIDE  1013
