## Data Types - Using an IStringTest 


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS =  /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : strngtst.exe 

strngtst.exe : strngtst.obj 
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) strngtst.obj

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp
