## Notebook Control - Simple Notebook Example


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS = /PM:PM /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : simple.exe 

simple.exe : simple.obj 
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) simple.obj

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp
