## Static Text Controls - Style Example 


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS = /PM:PM /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : textstyl.exe 

textstyl.exe : textstyl.obj 
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) textstyl.obj

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp
