## Problem Determination - Finding an Invisible Window


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS = /PM:PM /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : invisibl.exe 

invisibl.exe : invisibl.obj 
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) invisibl.obj

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp
