## Problem Determination - Termination Signal Handler


CFLAGS = -Tm /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS =  /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : sigterm.exe 

sigterm.exe : sigterm.obj 
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) sigterm.obj

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp
