## Using OS/2 Resources - Switching Resources Dynamically 


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS = /PM:PM /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : stattxt.exe myeng.dll

stattxt.exe : stattxt.obj
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) stattxt.obj

myeng.dll  : dummy.cpp mytext.h myeng.rc
   icc -Ge- -Gm /Femyeng.dll dummy.cpp myeng.def
   rc myeng.rc myeng.dll

dlltext.cpp : mytext.h

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp

