## Canvas - ISplitCanvas with Static Text Child Windows 


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS = /PM:PM /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : splittxt.exe 

splittxt.exe : splittxt.obj 
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) splittxt.obj

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp
