## Frame Window Basics - Defer Destroy on Frame Closing


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS = /PM:PM /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : dstrycls.exe 

dstrycls.exe : dstrycls.obj
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) dstrycls.obj

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp
