## Menus - Accessing the System Menu 


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS = /PM:PM /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : sysmenu.exe 

sysmenu.exe : sysmenu.obj 
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) sysmenu.obj

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp
