## Extending the Library - Value Set Example   


## CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ 
LFLAGS = /PM:PM /NOI
LIBS = dde4muii.lib dde4cci.lib
OBJS = testvset.obj valueset.obj vsethdr.obj vsetevt.obj

ALL : testvset.exe 

testvset.exe : testvset.res $(OBJS)
   icc $(CFLAGS) /B"$(LFLAGS)" /Fevalueset.exe $(LIBS) $(OBJS)
   rc .\$*.res valueset.exe

testvset.cpp  : valueset.hpp vsethdr.hpp testvset.h
valueset.cpp  : valueset.hpp
vsethdr.cpp   : valueset.hpp vsethdr.hpp
vsetevt.cpp   : vsetevt.hpp
testvset.rc   : testvset.h

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp

{.}.rc.res:
   rc -r .\$*.rc
