/************************************************************
/ Extending the Library - Value Set Example
/
/ Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
/ All Rights Reserved.
************************************************************/
#define M_STYLE            100
#define M_STYLE_BORDER     101
#define M_STYLE_ITEMBORDER 102
#define M_STYLE_RTL        103
#define M_STYLE_SCALE      104
#define M_STYLE_OWNERDRAW  105

#define M_DIMENSIONS                200
#define M_DIMENSIONS_QUERY          201
#define M_DIMENSIONS_SET            202
#define M_DIMENSIONS_ITEMSIZE       210
#define M_DIMENSIONS_ITEMSIZE_QUERY 211
#define M_DIMENSIONS_ITEMSIZE_SET   212
#define M_DIMENSIONS_SPACING        220
#define M_DIMENSIONS_SPACING_QUERY  221
#define M_DIMENSIONS_SPACING_SET    222
#define M_DIMENSIONS_MIN            230
#define M_DIMENSIONS_MIN_QUERY      231
#define M_DIMENSIONS_MIN_SIZE       232

#define M_ITEMS        300
#define M_ITEMS_BITMAP 301
#define M_ITEMS_COLOR  302
#define M_ITEMS_ICON   303
#define M_ITEMS_TEXT   304
                        
#define M_ITEMSTYLE           400
#define M_ITEMSTYLE_SET       401
#define M_ITEMSTYLE_ENABLE    402
#define M_ITEMSTYLE_DISABLED  403
#define M_ITEMSTYLE_DRAG      404
#define M_ITEMSTYLE_DROP      405
#define M_ITEMSTYLE_OWNERDRAW 406

#define M_COLORS         500
#define M_COLORS_BACK    501
#define M_COLORS_BORDERS 502
#define M_COLORS_FORE    503
#define M_COLORS_HILITE  504

#define ID_PALETTE 1
