## Canvas  - Simple IMultiCellCanvas Example            


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS = /PM:PM /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : mcsimple.exe 

mcsimple.exe : mcsimple.obj 
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) mcsimple.obj

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp
