## List Controls - Spin Button Date Control                  


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS = /PM:PM /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : spinbut.exe 

spinbut.exe : spinbut.obj datectrl.obj
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) spinbut.obj datectrl.obj

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp

spinbut.cpp :  datectrl.hpp
datectrl.cpp:  datectrl.hpp
