/************************************************************
/ Canvas - ISetCanvas Desks Example
/
/ Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
/ All Rights Reserved.
************************************************************/
#define  ID_TOP_LEFT       101
#define  ID_TOP_CENTER     102
#define  ID_TOP_RIGHT      103
#define  ID_CENTER_LEFT    104
#define  ID_CENTER_CENTER  105
#define  ID_CENTER_RIGHT   106
#define  ID_BOTTOM_LEFT    107
#define  ID_BOTTOM_CENTER  108
#define  ID_BOTTOM_RIGHT   109
