/************************************************************
/ Slider - Progress Indicator Example                 
/
/ Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
/ All Rights Reserved.
************************************************************/
#define ID_CANVAS         0x8008      // Canvas Window ID
#define ID_IND_TITLE      5000        // Indicator Title ID
#define ID_INDICATOR      5001        // Indicator Window ID
