## Container Control - Tree Icon View                 


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS = /PM:PM /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : treeicov.exe 

treeicov.exe : treeicov.obj treeicov.res
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) treeicov.obj
   rc .\$*.res .\$*.exe

treeicov.cpp  : treeicov.h
treeicov.rc   : treeicov.h

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp

{.}.rc.res:
   rc -r .\$*.rc
