## Resuable Handlers - Mouse Handler Example 


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS = /PM:PM /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : mouseclk.exe 

mouseclk.exe : mouseclk.obj 
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) mouseclk.obj

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp
