## Container Control - Tree Icon View                 


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS = /PM:PM /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : exviewer.exe 

exviewer.exe : exviewer.obj exviewer.res
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) exviewer.obj
   rc .\$*.res .\$*.exe

exviewer.cpp : exviewer.hpp exviewer.h
exviewer.rc  : exviewer.h

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp

{.}.rc.res:
   rc -r .\$*.rc
