## Thread - Executing a Thread with _OptLink Linkage


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS =  /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : optlink.exe 

optlink.exe : optlink.obj 
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) optlink.obj

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp
