## Data Types - Creating Dates and Times from IStrings 


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS =  /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : str2date.exe 

str2date.exe : str2date.obj 
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) str2date.obj

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp
