## Container Control - Tree Icon View                 


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS = /PM:PM /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : drawextn.exe 

drawextn.exe : drawextn.obj myframe.obj myextns.obj
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) drawextn.obj myframe.obj myextns.obj

drawextn.cpp  : myframe.hpp
myframe.cpp   : myframe.hpp myextns.hpp
myextns.cpp   : myextns.hpp

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp

{.}.rc.res:
   rc -r .\$*.rc
