## Using OS/2 Resources - Building a Resource DLL     


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS = /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : dlltext.exe myeng.dll

dlltext.exe : dlltext.obj
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) dlltext.obj

myeng.dll  : dummy.cpp mytext.h myeng.rc
   icc -Ge- -Gm /Femyeng.dll dummy.cpp myeng.def
   rc myeng.rc myeng.dll

dlltext.cpp : mytext.h

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp

