## Frame Window Basics - Modal Frame Window


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS = /PM:PM /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : modal.exe 

modal.exe : modal.obj 
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) modal.obj

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp
