/************************************************************
/ Lunch dialog - Dialog template implementation.             
/
/ Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
/ All Rights Reserved.
************************************************************/
#define ID_LUNCH_DIALOG   100
#define ID_LUNCH_TEXT     101
#define ID_FOOD           102
#define ID_HAMBURGER      103
#define ID_CHEESEBURGER   104
#define ID_HOTDOG         105
#define ID_PIZZA          106
#define ID_BEVERAGE       107
#define ID_MILK           108
#define ID_SOFTDRINK      109
#define ID_JUICE          110
#define ID_WATER          111
#define ID_SIDEORDERS     112
#define ID_SALAD          113
#define ID_FRIES          114
#define ID_REQUESTPROMPT  115
#define ID_REQUEST        116
#define ID_OK             1
#define ID_CANCEL         0x8004   // SC_CLOSE
#define ID_HELP           10
