/************************************************************
/ Menus - Dynamic Submenu Example
/
/ Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
/ All Rights Reserved.
************************************************************/
#define ID_EDIT            1002
                          
#define MAIN_MENU          1010
#define POPUP_MENU         1011
#define SECONDMAIN_MENU    1012

#define MI_FILE            1050
#define MI_NEW             1051
#define MI_OPEN            1052
#define MI_SAVE            1053
#define MI_SAVEAS          1054
#define MI_EDIT            1055
#define MI_UNDO            1056
#define MI_CUT             1057
#define MI_COPY            1058
#define MI_PASTE           1059
#define MI_READONLY        1060
#define MI_READWRITE       1061
#define MI_EXAMPLE         1062
#define MI_BITMAP          1063
#define MI_HELP            1064
#define MI_GENERAL_HELP    1065
#define MI_CASCADE         1066
#define MI_CASCADE1        1067
#define MI_CASCADE2        1068
#define MI_CASCADE3        1069
#define MI_SWITCH          1070
                          

