## Menus - Static Text Pop-up Example                 


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS = /PM:PM /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : txtpopup.exe 

txtpopup.exe : txtpopup.obj txtpopup.res
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) txtpopup.obj
   rc .\$*.res .\$*.exe

txtpopup.cpp : txtpopup.h
txtpopup.rc  : txtpopup.h

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp

{.}.rc.res:
   rc -r .\$*.rc
