// Window identifiers.
#define ID_PRIMARY                   1000
#define ID_LISTBOX                   1001
#define ID_PRIMARY2                  2000
#define ID_SECONDARY_MODELESS        3000
#define ID_SECONDARY_MODAL           4000
#define ID_CHILD_MODELESS            5000
#define ID_CHILD_MODAL               6000

// Generic window identifiers.
#define ID_CLIENT                    0x8008  // FID_CLIENT
#define ID_DUMMY                     1
#define ID_ENTRY1                    500
#define ID_ENTRY2                    501

// Menu bar identifiers.
#define ID_MENUBAR                   100
#define ID_FILE                      101
#define ID_HELP                      200
#define ID_USINGHELP                 201
#define ID_TUTORIAL                  202
#define ID_PRODUCTINFO               203

// Help table and subtable identifiers.
#define ID_HELPTABLE                 1000
#define SUBTABLE_PRIMARY             1
#define SUBTABLE_PRIMARY2            2
#define SUBTABLE_SEC_MODELESS        3
#define SUBTABLE_SEC_MODAL           4
#define SUBTABLE_CHILD_MODELESS      5
#define SUBTABLE_CHILD_MODAL         6

// Help panel identifiers.
#define PANEL_PRIMARY                1000
#define PANEL_LISTBOX                1001
#define PANEL_FILE                   1010
#define PANEL_CLOSE                  1011
#define PANEL_HELP                   1012
#define PANEL_HELPINDEX              1013
#define PANEL_EXTENDEDHELP           1014
#define PANEL_USINGHELP              1015
#define PANEL_KEYSHELP               1016
#define PANEL_TUTORIAL               1017
#define PANEL_PRODUCT_INFO           1018
#define PANEL_PRIMARY2               2000
#define PANEL_ENTRY1_PRIMARY2        2001
#define PANEL_SEC_MODELESS           3000
#define PANEL_ENTRY1_SEC_MODELESS    3001
#define PANEL_SEC_MODAL              4000
#define PANEL_ENTRY1_SEC_MODAL       4001
#define PANEL_CHILD_MODELESS         5000
#define PANEL_ENTRY1_CHILD_MODELESS  5001
#define PANEL_CHILD_MODAL            6000
#define PANEL_ENTRY1_CHILD_MODAL     6001
#define PANEL_KEYS_HELP              7000
#define PANEL_TUTORIAL_ERROR         8000
#define PANEL_PRODUCT_INFO_MSG       9000
