## Profile - Profile Viewer Example              


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS =  /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : viewprof.exe 

viewprof.exe :  viewprof.obj vprofarg.obj enhprof.obj
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) viewprof.obj vprofarg.obj enhprof.obj 
#   rc .\$*.res .\$*.exe

viewprof.cpp : vprofarg.hpp  enhprof.hpp
enhprof.cpp  : enhprof.hpp
vprofarg.cpp : vprofarg.hpp
keyview.cpp  : keyview.hpp profview.hpp
#profile.rc   : profview.h

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp

{.}.rc.res:
   rc -r .\$*.rc
