/*************************************************************/
/* Keyboard handler example for character keys.              */
/*                                                           */
/* Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.       */
/* All Rights Reserved.                                      */
/*************************************************************/
#define ID_KEYBD_DIALOG             100
#define ID_ANY_ENTRY                101
#define ID_UPPERCASE_ENTRY          102
#define ID_HEX_ENTRY                103
#define ID_UPPERCASE_HEX_ENTRY      104
#define ID_UPPERCASE_HEX_COMBO      105
#define ID_UPPERCASE_HEX_MLE        106
#define ID_CLOSE                    32772     // SC_CLOSE
