#ifdef _ACOLORW6_CPP_
#pragma alloc_text(ICLEXCEPTIONS, ICommandHandler::__dftbdt())
#pragma alloc_text(ICLEXCEPTIONS, IFrameWindow::__dftbdt())
#pragma alloc_text(ICLEXCEPTIONS, IRadioButton::__dftbdt())
#pragma alloc_text(ICLEXCEPTIONS, INotebook::PageSettings::__dftdt())
#endif

#ifdef _ADIALOG6_CPP_
#pragma alloc_text(ICLEXCEPTIONS, ICommandHandler::__dftbdt())
#pragma alloc_text(ICLEXCEPTIONS, IFrameWindow::__dftbdt())
#pragma alloc_text(ICLEXCEPTIONS, IString::__dftdt())
#endif

#ifdef _ADUMMY6_CPP_
#endif

#ifdef _AEARTHW6_CPP_
#pragma alloc_text(ICLEXCEPTIONS, IPaintHandler::__dftbdt())
#pragma alloc_text(ICLEXCEPTIONS, IStaticText::__dftbdt())
#endif

#ifdef _AHELLOW6_CPP_
#pragma alloc_text(ICLEXCEPTIONS, IRadioButton::__dftbdt())
#pragma alloc_text(ICLEXCEPTIONS, IMenuHandler::__dftbdt())
#pragma alloc_text(ICLEXCEPTIONS, IHelpHandler::__dftbdt())
#pragma alloc_text(ICLEXCEPTIONS, IHandler::__dftbdt())
#pragma alloc_text(ICLEXCEPTIONS, AHelloWindow::__dftdt())
#pragma alloc_text(ICLEXCEPTIONS, ATimeHandler::__dftbdt())
#pragma alloc_text(ICLEXCEPTIONS, ISelectHandler::__dftbdt())
#pragma alloc_text(ICLEXCEPTIONS, ICommandHandler::__dftbdt())
#pragma alloc_text(ICLEXCEPTIONS, ifstream::__dftdt())
#pragma alloc_text(ICLEXCEPTIONS, IProfile::__dftdt())
#pragma alloc_text(ICLEXCEPTIONS, IFont::__dftdt())
#pragma alloc_text(ICLEXCEPTIONS, IListBox::Cursor::__dftdt())
#pragma alloc_text(ICLEXCEPTIONS, IFontDialog::__dftdt())
#pragma alloc_text(ICLEXCEPTIONS, IFontDialog::Settings::__dftdt())
#pragma alloc_text(ICLEXCEPTIONS, IFileDialog::__dftdt())
#pragma alloc_text(ICLEXCEPTIONS, IFileDialog::Settings::__dftdt())
#pragma alloc_text(ICLEXCEPTIONS, IMessageBox::__dftdt())
#pragma alloc_text(ICLEXCEPTIONS, IFrameWindow::__dftbdt())
#pragma alloc_text(ICLEXCEPTIONS, IString::__dftdt())
#endif

#ifdef _ASPEEDW6_CPP_
#pragma alloc_text(ICLEXCEPTIONS, ICommandHandler::__dftbdt())
#pragma alloc_text(ICLEXCEPTIONS, IFrameWindow::__dftbdt())
#pragma alloc_text(ICLEXCEPTIONS, IString::__dftdt())
#endif

#ifdef _ATIMEHDR_CPP_
#pragma alloc_text(ICLEXCEPTIONS, IHandler::__dftbdt())
#endif

