#ifdef _ACOLORW6_CPP_
#pragma alloc_text(ICLStatics, AColorWindow::AColorButton::~AColorButton())
#pragma alloc_text(ICLBottom, ICommandHandler::__dftbdt())
#pragma alloc_text(ICLBottom, IFrameWindow::__dftbdt())
#pragma alloc_text(ICLBottom, IRadioButton::__dftbdt())
#pragma alloc_text(ICLBottom, INotebook::PageSettings::__dftdt())
#endif

#ifdef _ADIALOG6_CPP_
#pragma alloc_text(ICLBottom, ICommandHandler::__dftbdt())
#pragma alloc_text(ICLBottom, IFrameWindow::__dftbdt())
#pragma alloc_text(ICLBottom, IString::__dftdt())
#endif

#ifdef _AEARTHW6_CPP_
#pragma alloc_text(ICLStatics, AEarthWindow::~AEarthWindow())
#pragma alloc_text(ICLBottom, IPaintHandler::__dftbdt())
#pragma alloc_text(ICLBottom, IStaticText::__dftbdt())
#endif

#ifdef _AHELLOW6_CPP_
#pragma alloc_text(ICLStatics, AColorWindow::AColorButton::~AColorButton())
#pragma alloc_text(ICLStatics, AHelpHandler::~AHelpHandler())
#pragma alloc_text(ICLStatics, IHelpHandler::IHelpHandler())
#pragma alloc_text(ICLStatics, AMenuHandler::~AMenuHandler())
#pragma alloc_text(ICLStatics, IProfile::setDefaultApplicationName(const char*))
#pragma alloc_text(ICLStatics, AMenuHandler::AMenuHandler())
#pragma alloc_text(ICLStatics, AHelpHandler::AHelpHandler())
#pragma alloc_text(ICLStatics, ATimeHandler::~ATimeHandler())
#pragma alloc_text(ICLStatics, ATimeHandler::ATimeHandler())
#pragma alloc_text(ICLBottom, IRadioButton::__dftbdt())
#pragma alloc_text(ICLBottom, IMenuHandler::__dftbdt())
#pragma alloc_text(ICLBottom, IHelpHandler::__dftbdt())
#pragma alloc_text(ICLBottom, IHandler::__dftbdt())
#pragma alloc_text(ICLBottom, AHelloWindow::__dftdt())
#pragma alloc_text(ICLBottom, ATimeHandler::__dftbdt())
#pragma alloc_text(ICLBottom, ISelectHandler::__dftbdt())
#pragma alloc_text(ICLBottom, ICommandHandler::__dftbdt())
#pragma alloc_text(ICLBottom, ifstream::__dftdt())
#pragma alloc_text(ICLBottom, IProfile::__dftdt())
#pragma alloc_text(ICLBottom, IFont::__dftdt())
#pragma alloc_text(ICLBottom, IListBox::Cursor::__dftdt())
#pragma alloc_text(ICLBottom, IFontDialog::__dftdt())
#pragma alloc_text(ICLBottom, IFontDialog::Settings::__dftdt())
#pragma alloc_text(ICLBottom, IFileDialog::__dftdt())
#pragma alloc_text(ICLBottom, IFileDialog::Settings::__dftdt())
#pragma alloc_text(ICLBottom, IMessageBox::__dftdt())
#pragma alloc_text(ICLBottom, IFrameWindow::__dftbdt())
#pragma alloc_text(ICLBottom, IString::__dftdt())
#endif

#ifdef _ASPEEDW6_CPP_
#pragma alloc_text(ICLBottom, ICommandHandler::__dftbdt())
#pragma alloc_text(ICLBottom, IFrameWindow::__dftbdt())
#pragma alloc_text(ICLBottom, IString::__dftdt())
#endif

#ifdef _ATIMEHDR_CPP_
#pragma alloc_text(ICLStatics, ATimeHandler::~ATimeHandler())
#pragma alloc_text(ICLBottom, IHandler::__dftbdt())
#endif

