// Window identifiers.
#define ID_PRIMARY                   1000
#define ID_SECONDARY                 2000
#define ID_PAGE1                     2010
#define ID_ENTRY1                    2011
#define ID_ENTRY2                    2012
#define ID_ENTRY3                    2013
#define ID_PAGE2                     2020
#define ID_ENTRYA                    2021
#define ID_ENTRYB                    2022
#define ID_ENTRYC                    ID_ENTRY3
#define ID_PAGE3                     2030
#define ID_ENTRYX                    2031
#define ID_ENTRYY                    2032
#define ID_DIALOG                    3000
#define ID_DIALOG_ENTRY1             3001
#define ID_DIALOG_ENTRY2             3002

// Generic window identifiers.
#define ID_CLIENT                    0x8008  // FID_CLIENT
#define ID_DUMMY                     1

// Help table and subtable identifiers.
#define ID_HELPTABLE                 1000
#define SUBTABLE_PRIMARY             1
#define SUBTABLE_SECONDARY           2
#define SUBTABLE_PAGE3               3
#define SUBTABLE_DIALOG              4

// Help panel identifiers.
#define PANEL_PRIMARY                1000
#define PANEL_CONTAINER              1001
#define PANEL_PAGE1                  ID_PAGE1
#define PANEL_PAGE1_TAB              2011
#define PANEL_ENTRY1                 2012
#define PANEL_ENTRY3                 2013
#define PANEL_PAGE2                  ID_PAGE2
#define PANEL_PAGE2_TAB              2021
#define PANEL_ENTRYA                 2022
#define PANEL_ENTRYC                 2023
#define PANEL_PAGE3                  ID_PAGE3
#define PANEL_PAGE3_TAB              2031
#define PANEL_ENTRYX                 2032
#define PANEL_DIALOG                 2040
#define PANEL_DIALOG_TAB             2041
#define PANEL_DIALOG_ENTRY1          2042
#define PANEL_DROP                   3000
#define PANEL_NONE                   1
