## Container Control - Tree Icon View                 


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ 
LFLAGS = /PM:PM /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL :  setdecks.exe 

setdecks.exe : setdecks.obj deckcv.obj setdecks.res
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) setdecks.obj deckcv.obj
   rc setdecks.res .\$*.exe

setdecks.cpp: deckcv.hpp setdecks.h
deckcv.cpp: deckcv.hpp setdecks.h
setdecks.rc:  setdecks.h

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp

{.}.rc.res:
   rc -r .\$*.rc
