## Menus - Title Bar Bitmaps                          


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS = /PM:PM /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : titlebmp.exe 

titlebmp.exe : titlebmp.obj titlebmp.res
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) titlebmp.obj
   rc .\$*.res .\$*.exe

titlebmp.cpp : titlebmp.h
titlebmp.rc  : titlebmp.h

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp

{.}.rc.res:
   rc -r .\$*.rc
