/************************************************************
/ Container Control - Spreadsheet Behavior
/
/ Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
/ All Rights Reserved.
************************************************************/
#define SPD_ACCELERATOR 100

#define SPD_TAB         101
#define SPD_BACKTAB     102
#define SPD_UP          103
#define SPD_DOWN        104
#define SPD_OPEN        105

