## Frame Window Basics - Confirm Frame Closing


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS = /PM:PM /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : ok2close.exe 

ok2close.exe : ok2close.obj
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) ok2close.obj

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp
