/************************************************************
/ Slider - Slider Example
/
/ Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
/ All Rights Reserved.
************************************************************/
#define ID_CANVAS         0x8008      // Canvas Window ID
#define ID_SLD_TITLE      5000        // Slider Title ID
#define ID_SLIDER         5001        // Slider Window ID
#define ID_TEMP           5002        // Static Text Window ID
