## Container Control - Tree Text View


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS = /PM:PM /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : treetxtv.exe 

treetxtv.exe : treetxtv.obj 
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) treetxtv.obj

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp
