## Button Controls - Radio Button Select Handler


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS = /PM:PM /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : radio.exe 

radio.exe : radio.obj 
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) radio.obj
  
radio.cpp  : radio.h

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp
