/************************************************************
/ Button Controls - Radio Button Select Handler                 
/
/ Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
/ All Rights Reserved.
************************************************************/
#define ID_FILESTATIC  1000
#define ID_FILENAME    1001
#define ID_ENTRY1      1002
#define ID_ENTRY2      1003
#define ID_IMAGE       1004
#define ID_COLOR       1005
#define ID_CHANGECOLOR 1006
#define ID_STATUS      1007
#define ID_SET1        1008
#define ID_SET2        1009


