## Container Control - Text View


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS = /PM:PM /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : textview.exe 

textview.exe : textview.obj 
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) textview.obj

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp
