## Canvas - Group Box and Outline Box Example 


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS = /PM:PM /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : boxes.exe 

boxes.exe : boxes.obj 
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) boxes.obj

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp
