## Container - Keyboard Handler for MLE 


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS = /PM:PM /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : edithdr.exe 

edithdr.exe : edithdr.obj 
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) edithdr.obj

edithdr.cpp: keyhdr.hpp

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp
