## Frame Window Basics - Frame Extension Sampler


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS = /PM:PM /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : frmextns.exe 

frmextns.exe : frmextns.obj
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) frmextns.obj

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp
