## Text Controls - Static Text Color Example 


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS = /PM:PM /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : textclr.exe 

textclr.exe : textclr.obj 
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) textclr.obj

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp
