## Canvas - Static Text on a Canvas  Example 


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS = /PM:PM /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : textcv.exe 

textcv.exe : textcv.obj 
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) textcv.obj

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp
