/************************************************************
/ Tour of the UICL - Shopping List Example Program
/
/ Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
/ All Rights Reserved.
************************************************************/
#define ID_CSETPLUSPLUSICON    100

#define ID_CLIENT              0x8008  // (FID_CLIENT)

// Primary window identifiers.
#define ID_SHOPPINGLIST        1000
#define ID_LISTCLIENT          ID_CLIENT
#define ID_BUYLIST             1001
#define ID_DONTBUYLIST         1002

// PurchaseItem view window identifiers.
#define ID_PURCHASEITEMVIEW    2000
#define ID_PURCHASEITEMBOOK    ID_CLIENT
#define ID_PURCHASEITEMPAGE1   2001
#define ID_NAMEPROMPT          2002
#define ID_NAME                2003
#define ID_QUANTITYPROMPT      2004
#define ID_QUANTITY            2005
#define ID_MANUFACTURERPROMPT  2006
#define ID_MANUFACTURER        2007
#define ID_PRICEPROMPT         2008
#define ID_PRICE               2009
#define ID_NOTESPROMPT         2010
#define ID_NOTES               2011
#define ID_PURCHASEITEMPAGE2   2012
#define ID_FILEDIALOG          3000
