/************************************************************
/ Canvas - IViewPort that Scrolls a Bitmap.
/
/ Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
/ All Rights Reserved.
************************************************************/
#define ID_BITMAP                 100
#define ID_DEFAULTBMP             101
#define ID_FLAMINGO               101
#define ID_BUTTERFLIES            102
#define ID_SHELLS                 103
#define ID_ORCHIDS                104
#define ID_OS2LOGO                105

#define ID_DOUBLE_SIZE            201
#define ID_HALVE_SIZE             202

#define ID_VIEWPORT               300
#define ID_SCROLL_TO_TOP          301
#define ID_SCROLL_TO_VERT_MIDDLE  302
#define ID_SCROLL_TO_BOTTOM       303
#define ID_SCROLL_TO_LEFT         304
#define ID_SCROLL_TO_MIDDLE       305
#define ID_SCROLL_TO_RIGHT        306
