/************************************************************
/ Button Controls  - Push Button Example
/
/ Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
/ All Rights Reserved.
************************************************************/
#define ID_TEXT1      1000
#define ID_TEXT2      1001
#define ID_ENTRY1     1002
#define ID_ENTRY2     1003
#define ID_OK         1004
#define ID_CANCEL     1005
#define ID_HELP       1006
#define ID_STATUS     1007
#define ID_BUTTONS    1008
#define ID_BITMAPBUTTON 1009
#define ID_ICONBUTTON   1010


