## Notebook Control - Adding Notebook Windows to a Viewport


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS = /PM:PM /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : vportdlg.exe

vportdlg.exe : vportdlg.obj vportdlg.res
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) vportdlg.obj
   rc .\$*.res .\$*.exe

vportdlg.cpp:  vportdlg.h deferacc.hpp
vportdlg.rc:  vportdlg.h


{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp

{.}.rc.res:
   rc -r .\$*.rc
