## Problem Determination - Simple Catch Dialog


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS = /PM:PM /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : excdisp.exe 

excdisp.exe : excdisp.obj 
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) excdisp.obj

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp
