## Canvas  - Simple ICanvas Example            


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS = /PM:PM /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : vportlog.exe 

vportlog.exe : vportlog.obj 
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) vportlog.obj

vportlog.cpp: vportlog.hpp

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp
