/************************************************************
/ Container Control - Help in the Container
/
/ Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
/ All Rights Reserved.
************************************************************/
#define HELP_TABLE              500
#define SUBTABLE_DETAILS        501
#define SUBTABLE_SETTINGS       502
#define HELP_LIBRARIES          503

#define HELPFOR_DETAILS         510
#define HELPFOR_SETTINGS        511
#define HELPFOR_ADDRESS_SETTINGS  512
#define HELPFOR_PERSONAL_SETTINGS 513
#define HELPFOR_NAME            514
#define HELPFOR_ADDRESS         515
#define HELPFOR_AGE             516
#define HELPFOR_DEVELOPER       517
#define HELPFOR_UNDO            518
#define HELPFOR_DEFAULT         519
#define HELPFOR_DEVELOPERLIST   520
#define HELPFOR_OPEN            521

#define ID_DETAILS_FRAME       1000
#define ID_DETAILS_CNR         1001
#define ID_SETTINGS_FRAME      1007
#define ID_SETTINGS_NOTEBOOK   1008
#define ID_SETTINGS_PAGE1      1009
#define ID_SETTINGS_PAGE2      1010
#define ID_NAME_TEXT           1011
#define ID_ADDRESS_TEXT        1012
#define ID_AGE_TEXT            1013
#define ID_NAME_EDIT           1014
#define ID_ADDRESS_EDIT        1015
#define ID_AGE_EDIT            1016
#define ID_HELP_PAGE1          1017
#define ID_UNDO_PAGE1          1018
#define ID_DEFAULT_PAGE1       1019
#define ID_HELP_PAGE2          1020
#define ID_UNDO_PAGE2          1021
#define ID_DEFAULT_PAGE2       1022
#define ID_PAGE1_BUTTONS       1023
#define ID_PAGE2_BUTTONS       1024
#define ID_DETAILS_OPEN        1025

#define STR_OPEN               1200

