## Menus  - Using an IMenuBar                         


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS = /PM:PM /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : menubar.exe 

menubar.exe : menubar.obj menubar.res
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) menubar.obj
   rc .\$*.res .\$*.exe

menubar.cpp : menubar.h
menubar.rc  : menubar.h

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp

{.}.rc.res:
   rc -r .\$*.rc
