## Canvas  - Simple ICanvas Example            


CFLAGS = /Tdp /Gd+ /Ge+ /Gm+ /Wall+ext-gnr-got-por-ppt-uni-vft-
LFLAGS = /PM:PM /NOI
LIBS = dde4muii.lib dde4cci.lib

ALL : cvsimple.exe 

cvsimple.exe : cvsimple.obj 
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) cvsimple.obj

{.}.cpp.obj:
   icc $(CFLAGS) /C+ .\$*.cpp
